FROM python:3.9

WORKDIR /app

COPY ./backend /app

RUN pip install -r requirements.txt

RUN python manage.py makemigrations account

RUN python manage.py makemigrations payments

RUN python manage.py makemigrations product

RUN chmod +x /app/django_start.sh

EXPOSE 8000

ENTRYPOINT ["./django_start.sh"]