FROM node:14

WORKDIR /app

COPY ./frontend /app

RUN pip install -r requirements.txt

RUN npm ci

EXPOSE 3000

# Set environment variable for Node.js
ENV NODE_OPTIONS=--openssl-legacy-provider

CMD ["npm", "start"]