version: '3.8'

services:
  backend:
    image: jonwang22/ecommerce_backend:latest
    environment:
      - DB_HOST=${rds_endpoint}
      - RUN_MIGRATIONS=${run_migrations}
    ports:
      - "8000:8000"
    command: >
          sh -c "set -e &&
                if [[ '${RUN_MIGRATIONS}'' == 'true' ]]; then
                    echo 'Running initial migration and data loading...' &&
                    python manage.py migrate && 
                    python manage.py dumpdata --database=sqlite --natural-foreign --natural-primary -e contenttypes -e auth.Permission --indent 4 > datadump.json &&
                    python manage.py loaddata datadump.json
                else
                    echo 'Migration already completed' &&
                    python manage.py migrate;
                fi &&
                [ -f db.sqlite3 ] && rm -f db.sqlite3 &&
                python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: jonwang22/ecommerce_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
