version: '3.8'

services:
  backend:
    image: jonwang22/ecommerce_backend:latest
    environment:
      - DB_HOST=${rds_endpoint}
      - RUN_MIGRATIONS=${run_migrations}
    ports:
      - "8000:8000"

  frontend:
    image: jonwang22/ecommerce_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
